source 'http://rubygems.org'

gemspec

gem 'pry', :require => 'pry' if ENV['PRY']
gem 'perftools.rb', :require => 'perftools' if ENV['PERFTOOLS']

group :test do
  gem 'ci_reporter',   '~> 1.7.0', :require => nil
  gem 'test-unit'      if RUBY_VERSION.to_f >= 1.9
  gem 'mocha',         '~> 0.12.1'
  gem 'simplecov',     '~> 0.6.4', :require => nil
  gem 'webmock',       '~> 1.6.4'
  gem 'poltergeist',   '~> 1.2.0'
  gem 'capybara',      '~> 2.1.0'

  # Note:  Only for CI output
  gem 'rspec-core',    '~> 2.8', :require => nil
end

group :test, :development do
  gem 'konacha',       '~> 2.6.0'
end

group :assets do
  gem 'compass-rails', '~> 1.0.3'
  gem 'sass-rails',    '~> 3.2.5'
  gem 'coffee-rails',  '~> 3.2.2'
  gem 'jquery-rails',  '~> 2.0.2'
  gem 'uglifier',      '>= 1.2.6'
  gem 'therubyracer',  '>= 0.10'
end

